
CREATE ROLE scm LOGIN PASSWORD '1qaz2ws';
CREATE ROLE amon LOGIN PASSWORD '1qaz2ws';
CREATE ROLE hue LOGIN PASSWORD '1qaz2ws';
CREATE ROLE nav LOGIN PASSWORD '1qaz2ws';
CREATE ROLE rman LOGIN PASSWORD '1qaz2ws';
CREATE ROLE metastore LOGIN PASSWORD '1qaz2ws';
CREATE ROLE sentry LOGIN PASSWORD '1qaz2ws';
CREATE ROLE navms LOGIN PASSWORD '1qaz2ws';
CREATE ROLE oozie LOGIN PASSWORD '1qaz2ws';


CREATE DATABASE scm OWNER scm ENCODING 'UTF8';
CREATE DATABASE amon OWNER amon ENCODING 'UTF8';
CREATE DATABASE rman OWNER rman ENCODING 'UTF8';
CREATE DATABASE hue            OWNER hue ENCODING 'UTF8';
CREATE DATABASE metastore      OWNER metastore ENCODING 'UTF8';
CREATE DATABASE sentry         OWNER sentry ENCODING 'UTF8';
CREATE DATABASE nav            OWNER nav ENCODING 'UTF8';
CREATE DATABASE navms          OWNER navms ENCODING 'UTF8';
CREATE DATABASE oozie          OWNER oozie ENCODING 'UTF8';
